version: '3.5'

services:
  adaptor:
    image: adaptor
    container_name: adaptor
    build: ./adaptor
    restart: always
    command: python3 -u aggregator.py
    environment:
      - DEBUG_DATA_FLOW=true
    depends_on:
      - broker
      - influxdb
    networks:
      - adaptor-broker
      - adaptor-db

  broker:
    image: eclipse-mosquitto:1.6
    hostname: broker-container                                                                    
    ports:
      - '1883:1883'
    networks:
      - adaptor-broker                                                                                                                                                                     
    # volumes:
    #   - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  influxdb:
    image: influxdb:1.8
    hostname: db-container
    volumes:
    - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=root
      - INFLUXDB_ADMIN_PASSWORD=pass
    ports:
      - "8086:8086"
    networks:
      - adaptor-db
      - grafana-db

  grafana:
    image: grafana/grafana:8.2.6
    ports:
      - '80:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=asistent
      - GF_SECURITY_ADMIN_PASSWORD=grafanaSPRC2021
    volumes:
      - ./grafana-provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana-provisioning/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - influxdb
    networks:
      - grafana-db

volumes:
  grafana-storage: {}
  influxdb-storage: {}

networks:
  grafana-db:
    name: grafana-db
  adaptor-db:
    name: adaptor-db
  adaptor-broker:
    name: adaptor-broker