version: '3.5'

services:
  broker:
    image: eclipse-mosquitto:1.6                                                                     
    ports:
      - '1883:1883'                                                                                                                                                                           
    # volumes:
    #   - ./mosquitto.conf:/mosquitto/config/mosquitto.conf